pagopa/pagopa-ecommerce-local

pagopa-ecommerce-transactions-service/Dockerfile.transactions-service
updated docker file to start ecommerce-local 
add -Dskiptests to transaction-service
add --enable-preview to CMD line
=> fix dockerfile to start ecommerce-locale

pagopa-ecommerce-payment-instruments-service/Dockerfile.payment-instruments-service, pagopa-ecommerce-payment-requests-service/Dockerfile.payment-requests-service, pagopa-ecommerce-scheduler-service/Dockerfile.scheduler-service, pagopa-ecommerce-sessions-service/Dockerfile.sessions-service, pagopa-ecommerce-transactions-service/Dockerfile.transactions-service
Add option to skip tests during modules builds
=> fix: add skip tests during module builds

pagopa-notifications-service/Dockerfile.notifications-service
Align notifications-service node.js version as for PR: pagopa/pagopa-notifications-service#26
=> fix: align node.js notification service version

docker-compose.yml, gec-mock/Dockerfile.gec-mock, gec-mock/api-config-server.json, gec-mock/middleware.js, gec-mock/routes.json
Add jsonserver gec mock to ecommerce local
=> add gec-mock to ecommerce local

pagopa-ecommerce-transactions-service/transactions-service.env
Added new queue name into transaction-service env.
=> Added queue name

pagopa-personal-data-vault-tokenizer/src/db.json
=> [CHK-1296] fix: pagopa-pdv mock response

azurite-init/Dockerfile.azurite-init
Fix problem azurite-init dockerfile during copy env file
=> fix-azurite-init-dockerfile

docker-compose.yml, pagopa-ecommerce-event-dispatcher-service/Dockerfile.event-dispatcher-service
fix event dispatcher docker file
=> fix: event dispatcher docker file

pagopa-ecommerce-transactions-service/transactions-service.env
Add env properties for transaction service
Add env properties for transaction service
expected)
=> fix: add transaction service env properties

pagopa-ecommerce-transactions-service/transactions-service.env, pagopa-notifications-service/notifications-service.env, pagopa-personal-data-vault-tokenizer/src/db.json, pagopa-personal-data-vault-tokenizer/src/routes.json
- Modified the json server's **/tokens/:token/pii** api response to allow separate handling of the response to be returned to the notification-service from that for the transaction-service
- In addition, variables were added for the integration of **PDV** on the notification-service
The change was made to add the env variables for the integration of PDV on the notification-service
expected)
=> CHK-1513-added-pdv-mock-notification-service

pagopa-ecommerce-payment-requests-service/payment-requests-service.env
-  add pdv config for `pagopa-ecommerce-payment-requests`
expected)
=> feat: CHK-1656 add pdv config for payment-requests

pagopa-ecommerce-payment-requests-service/Dockerfile.payment-requests-service, pagopa-ecommerce-transactions-scheduler-service/Dockerfile.transactions-scheduler-service
Fix java agent option in env service files
Fix java agent option in payment request and transaction scheduler
Ecommerce locan didn't run payment-reqeust and transaction-scheduler
expected)
=> Fix java agent option in payment request and transaction scheduler

api-tests/transaction-service/transaction-service_ecommerce_local.postman_collection.json
Added GET transaction test into transaction collection
expected)
=> feat(transaction collection): added GET transaction test

api-tests/payment-method-service/payment-method-service_ecommerce_local.postman_collection.json, api-tests/payment-method-service/payment-method-service_ecommerce_local.postman_environment.json, api-tests/transaction-service/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/transaction-service_ecommerce_local.postman_environment.json
Fixed payment method collection test and transaction collection test
expected)
=> fix(orderId): payment method collection

api-tests/transaction-service/transaction-service_ecommerce_local.postman_collection.json
=> feat: added new header x pgs id

pagopa-ecommerce-transactions-service/transactions-service.env
=> feat: add ff for sendpamentresult

api-tests/payment-method-service/payment-method-service_ecommerce_local.postman_collection.json
Added size check and prefix check for orderId into payment method collection tests
expected)
=> [CHK-2096] feat: added orderId check into payment method collection tests

pagopa-ecommerce-transactions-service/transactions-service.env
Fix transactions service NODO_PER_PM_URI
ix transactions service NODO_PER_PM_URI
expected)
=> fix: transactions service NODO_PER_PM_URI

npg-mock/middleware.js, npg-mock/npg-server.json, npg-mock/routes.json
Add NPG `order/build` APM and CARDS response differentiation
This modification is needed in order to properly handle NPG different responses for CARDS and PAYPAL payment service `order/build` api call
expected)
=> feat: add order build npg mock for CARDS and APM

npg-mock/Dockerfile.npg-mock, pgs-mock/Dockerfile.pgs-mock, wallet-mock/Dockerfile.wallet-mock
Upgrade node version for json server mocks
Upgrade node version for json server mocks
expected)
=> fix: increase node version

gec-mock/Dockerfile.gec-mock
Fix GEC mock node version
Fix GEC mock node version
expected)
=> fix: gec mock node version

gec-mock/Dockerfile.gec-mock, npg-mock/Dockerfile.npg-mock, pgs-mock/Dockerfile.pgs-mock, wallet-mock/Dockerfile.wallet-mock
Use json server fixed version instead of latest for mock build reproducibility
Use json server fixed version instead of latest for mock build reproducibility
expected)
=> fix(json-server-mock): use json server fixed version

api-tests/payment-method-service/payment-method-service_ecommerce_local.postman_collection.json
* add new `methodManagement` field to API tests
expected)
=> [CHK-2322] feat(payment-methods): add new `methodManagement` field to API tests

api-tests/transaction-service/npg/transaction-service_ecommerce_local.postman_collection.json
=> [CHK-2322] fix(redirect): add `methodManagement` field to pre-request script in transactions-service api tests

api-tests/transaction-service/pgs/vpos/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/pgs/xpay/transaction-service_ecommerce_local.postman_collection.json
=> fix(api-test): add `methodManagement` field for PGS API tests when creating payment method

psp-mock/middleware.js
* add required field `touchpoint` in Redirect url retrieval API
See pagopa/pagopa-ecommerce-transactions-service#403
expected)
=> [CHK-2366] feat(redirect): add required field `touchpoint` in Redirect url retrieval API

api-tests/transaction-service/npg/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/pgs/vpos/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/pgs/xpay/transaction-service_ecommerce_local.postman_collection.json
Fix api tests expected body
Fix api tests expected body
expected)
=> fix(api-tests): change expected response body for get transactions

api-tests/transaction-service/npg/transaction-service_ecommerce_local.postman_collection.json
fixed prescript user receipt for NPG
expected)
=> fix: prescript user receipt NPG

api-tests/transaction-service/npg/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/pgs/vpos/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/pgs/xpay/transaction-service_ecommerce_local.postman_collection.json
=> feat: added NOTITICATION_ERROR into response test for get transactionId

api-tests/transaction-service/redirect/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/redirect/transaction-service_ecommerce_local.postman_environment.json
=> fix: added correlationid into redirect collection

psp-mock/middleware.js
Allow both redirections and forward paths into psp mock
Allow both redirections and forward paths into psp mock
expected)
=> fix(psp-mock): allow both redirections and forward paths

psp-mock/middleware.js
Pretty print requests headers and body for psp mock in order to make local tests debug easier
Pretty print requests headers and body for psp mock in order to make local tests debug easier
Local tests with eCommere local
expected)
=> chore(psp-mock): pretty print requests headers and body

gec-mock/gec-server.json
Add `pspBusinessName` to gec mock response
expected)
=> [CHK-2609] update gec mock

api-tests/transaction-service/npg/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/redirect/transaction-service_ecommerce_local.postman_collection.json
Update transactions-service api tests for NPG and REDIRECT collections:
- add user receipt request calculated dinamically taking informations from `POST transactions` eCommerce response (such as paymentToken)
- add test to check KO in case of addUserReceipt payment token mismatch
Those modifications are needed to correctly build add user receipt request
local collection run with eCommerce local
expected)
=> Chk 2794 send payment result data

api-tests/transaction-service/npg/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/npg/transaction-service_ecommerce_local.postman_environment.json
depends on https://github.com/pagopa/io-pagopa-node-mock/pull/59
- add integration test for convention pagoPA
The goal of this PR is to add api test for local env (running in code review ecommerce pipelinea) to test conventions pagoPA.
expected)
=> test: CHK-353 add integration test for convention pagoPA

pagopa-notifications-service/Dockerfile.notifications-service
- Upgrade node version from 18 to 20 of notification-service
The goal of this PR is to update node version to the next LTS available of the notification-service docker, because node 18 support ends on 30 April 2025.
> Support for Node.js 18 ends on 30 April 2025—upgrade your apps to Node.js 20 
expected)
=> [CHK-3672] feat: upgrade node version of notification-service from 18 to 20

pagopa-notifications-service/Dockerfile.notifications-service
- Upgrade node version to 22 of notification-service with slim version instead alpine
The goal of this PR is to use node 22 container slim version instead alpine due to memory/cpu issues detected on started container.
expected)
=> [CHK-3672] feat: upgrade to node to 22

pagopa-ecommerce-payment-requests-service/payment-requests-service.env, pagopa-ecommerce-transactions-service/transactions-service.env
Updated env vars to reflect latest updates on respective services
expected)
=> [CHK-4025] Updated env vars

api-tests/transaction-service/npg/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/redirect/transaction-service_ecommerce_local.postman_collection.json
Fix PATCH auth request test condition to include NOTIFICATION_REQUESTED and NOTIFIED_OK state to the valid ones
Fix PATCH auth request test condition to include NOTIFICATION_REQUESTED and NOTIFIED_OK state to the valid ones
expected)
=> fix: patch auth request condition

api-tests/transaction-service/npg/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/redirect/transaction-service_ecommerce_local.postman_collection.json
- added API tests on transactions-service for GET transaction outcome (NPG and REDIRECT)
This change was needed to have a complete integration test run after adding the new get transaction outcome API on ecommerce-transactions-service
- Tested running the docker containers locally and calling the API through postman 
expected)
=> feat(api-test): [CHK-4118] add transaction outcome api test

docker-compose.yml, npg-mock/Dockerfile.npg-mock, pagopa-jwt-issuer-mock/Dockerfile.jwt-issuer-mock, wallet-mock/Dockerfile.wallet-mock
Fix port mapping for jwt token issuer mock
remove unused expose port instruction
those modifications are needed in order to let use jwt token issuer service mock from localhost
local test
expected)
=> chore: fix mock for localhost use

api-tests/transaction-service/npg/transaction-service_ecommerce_local.postman_collection.json, api-tests/transaction-service/redirect/transaction-service_ecommerce_local.postman_collection.json
FIx status to be check condition from wrong NOTIFIED_ERROR to right NOTIFICATION_ERROR
FIx status to be check condition from wrong NOTIFIED_ERROR to right NOTIFICATION_ERROR
expected)
=> chore: fix status to be check

pagopa-ecommerce-cdc-service/ecommerce-cdc-service.env
- added the environment variable to configure the transactions view collection name for ecommerce-cdc-service  integrations tests 
expected)
=> feat(ecommerce-cdc): [CHK-4352] add view name env var
